header:
  message: 这是 `banned-players.json` 中根数组中的一个条目。
uuid:
  description: 代表被封禁用户的 UUID。
  default: 被封禁用户的 UUID
name:
  description: 被封禁用户的名称。
  default: 被封禁用户的名称。
created:
  description: |
    被封禁用户的名称。
    预期的格式是“yyyy-MM-dd HH:mm:ss Z”。
  default: 封禁创建时间
source:
  description: 一个表示封禁来源的字符串。
  default: '"(未知)"'
expires:
  description: |
    封禁到期的时间戳，如果封禁永不到期则为“永久”。

    预期的格式是“yyyy-MM-dd HH:mm:ss Z”。
  default: '"永久"'
reason:
  description: 封禁的原因。
  default: '"被管理员封禁。"'
