command-block-overrides:
  default: "[<要覆盖的命令>]"
  description: >
    哪些原版命令应该优先于 Bukkit 或插件提供的命令。
    这对于与为原版命令方块制作的冒险地图的兼容性很有用。

    使用文字 ''*'' 来始终在命令方块中使用原版版本。

    默认情况下，没有命令被覆盖。
ignore-vanilla-permissions:
  default: "false"
  description: 是否在执行命令时使用原版权限等级。
aliases:
  <别名名称>:
    default: "[<要运行的命令>]"
    description: >
      一个字符串列表，表示目标命令。
      或者是一个字符串，表示单个目标命令。

      目标命令是在运行别名时运行的命令。

      替换:

        * `$sender` 被替换为命令发送者的名称（由 Paper 添加）。
        * `$<n>` 被替换为第 n 个参数，从 1 开始索引。
        * `$$<n>` 被替换为第 n 个参数，从 1 开始索引，如果第 n 个参数不存在则失败。
        * `$<n>-` 被替换为第 n 个参数及其之后的所有内容，从 1 开始索引。
        * `$$<n>-` 被替换为第 n 个参数及其之后的所有内容，从 1 开始索引，如果第 n 个参数不存在则失败。


      每个注册的别名都不能（轻易地）被插件覆盖。
  icanhasbukkit:
    default: "[version $1-]"
    description: >-
      每个注册的别名都不能（轻易地）被插件覆盖。
