header:
  message: |
    #通过将以下设置更改为 TRUE，您表示同意我们的 EULA（[https://aka.ms/MinecraftEULA](https://aka.ms/MinecraftEULA)）。 C.

    #\<date\>
  inline: true
eula:
  default: "false"
  description: >-
    是否接受 Minecraft EULA。
    必须将其设置为“true”才能运行服务器。
