general-topics:
  <主题名称>:
    header:
      message: 当用户输入“`/help <topic>`”时显示的自定义帮助“主题”。
    shortText:
      description: |
        帮助条目的第一行，用作索引页面中的摘要。

        这是用旧版“&”样式格式化的。
    fullText:
      description: |
        这个帮助条目的剩余行。

        这是用旧版 “&” 样式格式化的。
    permission:
      description: |
        查看此帮助条目所需的权限。

        如果此值为空或未设置，则该条目不需要权限。

index-topics:
  <主题名称>:
    header:
      message: |
        一个复合帮助主题索引。

        如果主题名称是特殊值 “Default”，
        它将覆盖用于`/help`（无参数）的自动生成的索引。
    shortText:
      description: |
        在其他索引主题中使用的简短文本。

        在显示此主题本身时不显示。

        这是用旧版 “&” 样式格式化的。
    preamble:
      description: |
        在索引之前显示的信息。

        这是用旧版 “&” 样式格式化的。
    permission:
      description: |
        查看此帮助条目所需的自定义权限。

        如果此值为空或未设置，则该条目不需要权限。
    commands:
      description: |
        在索引中显示的内容。

        这是一个命令列表，或者其他帮助主题。

        它们将以“主题名称：简短文本”的格式按此处列出的顺序显示。

        每个条目最多为 1 行最小宽度的聊天行（55个字符）。
      default: "[]"

amended-topics:
  <主题名称>:
    shortText:
      description: |
        用于替换该主题的简短文本。

        如果此值为空或未设置，则使用原始的简短文本。

        如果此值包含字面字符串 `<text>`，它将被替换为原始的简短文本。

        这是用旧版“&”样式格式化的。
    fullText:
      description: |
        用于替换该主题的完整文本。

        如果此值为空或未设置，则使用原始的完整文本。

        如果此值包含字面字符串 `<text>`，它将被替换为原始的完整文本。

        这是用旧版“&”样式格式化的。
    permission:
      description: |
        覆盖查看此帮助条目所需的权限。

        如果此值为空或未设置，则不使用原始权限，而是不需要任何权限。

ignore-plugins:
  description: |
    一个列表，列出在为注册命令生成帮助主题时要忽略的插件。

    如果包含 “All”，则忽略所有插件。

    如果包含特殊的插件名称 “Bukkit”，则忽略由 Bukkit 注册的所有命令。
  default: "[]"

command-topics-in-master-index:
  description: |
    是否允许命令主题（以`/`开头的主题）显示在主索引中。

    这是当用户输入“`/help`”或“`/help <page>`”时显示的索引。
    命令别名主题始终被隐藏。
  default: "true"
