header:
  message: 这是在 `ops.json` 中根数组的一个条目。
uuid:
  description: 代表管理员的UUID。
  default: 管理员的UUID
name:
  description: 管理员的名字。
  default: 管理员的名称
level:
  description: |
    管理员权限的等级。

    预期的格式是 0 到 4 之间的整数。
  default: "0"

bypassesPlayerLimit:
  description: 该管理员是否绕过玩家限制。
  default: "false"
