anticheat:
  obfuscation:
    items:
      all-models:
        also-obfuscate:
          default: "[]"
          description: >-
            设置应向其他玩家隐藏的所有物品的附加数据组件。

            - 除非您知道自己在做什么，否则通常不建议配置此选项，因为您可能会改变物品在玩家眼中的外观。
        dont-obfuscate:
          default: "[minecraft:lodestone_tracker]"
          description: >-
            设置不应向其他玩家隐藏的所有物品的数据组件。

            - 这是因为它们可能会略微改变物品的外观，因此隐藏它们是没有必要的。在这个例子中，磁石追踪器可能会暴露关键位置，但隐藏位置会导致指南针在其他玩家面前晃动。是否认为这种权衡很重要，取决于您的判断。
        sanitize-count:
          default: "true"
          description: >-
            是否对其他玩家隐藏物品的数量。
      enable-item-obfuscation:
        default: "false"
        description: >-
          是否将可能为作弊客户端提供优势的不必要的物品信息（如附魔、物品说明等）发送给其他玩家的客户端。

          - 这可能会破坏依赖于附魔、物品说明或物品名称等信息来观察其他玩家的资源包。可以通过 `also-obfuscate` 扩展或通过 `dont-obfuscate` 减少隐藏的数据组件。
      model-overrides:
        minecraft:elytra:
          also-obfuscate:
            default: "[]"
            description: >-
              设置具有 `minecraft:elytra` 物品模型的物品还应混淆的组件。

              - 如果你希望隐藏对其他玩家不重要的某些组件，这可能会很有用。
          dont-obfuscate:
            default: "[minecraft:damage]"
            description: >-
              设置具有 `minecraft:elytra` 物品模型的物品不应混淆的组件。

              - 默认为 `minecraft:damage`，因为耐久度为 1 的鞘翅有特殊的纹理。
          sanitize-count:
            default: true
            description: >-
              是否对其他玩家隐藏具有 `minecraft:elytra` 模型的物品的数量。
block-updates:
  disable-noteblock-updates:
    default: "false"
    description: >-
      是否禁用音符盒的所有方块更新形式。

      - 禁用方块更新将导致音符盒不再更新其方块状态，允许在世界中保留技术上无效的音符盒，这可能对地图制作者有用。
  disable-tripwire-updates:
    default: "false"
    description: >-
      是否禁用绊线钩的所有方块更新形式。

      - 禁用方块更新将导致绊线钩不再更新其方块状态，允许在世界中保留技术上无效的绊线钩，这可能对地图制作者有用。
  disable-chorus-plant-updates:
    default: "false"
    description: >-
      是否禁用紫颂植株的所有方块更新形式。

      - 禁用方块更新将导致紫颂植株不再更新其方块状态，允许在世界中保留技术上无效的紫颂植株配置，这可能对地图制作者有用。
  disable-mushroom-block-updates:
    default: "false"
    description: >-
      是否禁用蘑菇方块的所有方块更新形式。

      - 禁用方块更新将导致蘑菇方块不再更新其方块状态，允许在世界中保留技术上无效的蘑菇方块配置，这可能对地图制作者有用。
chunk-loading-advanced:
  auto-config-send-distance:
    default: "true"
    description: >-
      是否匹配客户端在其视距设置中配置的区块发送半径（前提是客户端的设置小于服务器的发送距离），则设置为 `true`。
  player-max-concurrent-chunk-generates:
    default: "0"
    description: >-
      设置单个玩家可以拥有的最大并发区块生成数量。

      - 设置为 `0` 以让服务器为每个玩家自动配置，或设置为 `-1` 以禁用限制。
  player-max-concurrent-chunk-loads:
    default: "0"
    description: >-
      设置单个玩家可以拥有的最大并发区块加载数量。

      - 设置为 `0` 以让服务器为每个玩家自动配置，或设置为 `-1` 以禁用限制。
chunk-loading-basic:
  player-max-chunk-generate-rate:
    default: "-1.0"
    description: >-
      设置单个玩家的区块生成的最大速率。

      - 设置为 `-1` 以禁用此限制。
  player-max-chunk-load-rate:
    default: "100"
    description: >-
      设置单个玩家的区块加载的最大速率。

      - 请注意，此设置也会影响区块生成，因为区块加载总是首先发出以测试区块是否已经生成。设置为 `-1` 以禁用此限制。
  player-max-chunk-send-rate:
    default: "75"
    description: >-
      设置向每个玩家发送区块的最大速率，单位为每秒区块数。

      - 设置为 `-1` 以禁用此限制。
chunk-system:
  gen-parallelism:
    default: default
    description: >-
      设置服务器是否使用并行区块生成。

      - 可以配置的选项是 `true`、`on` 和 `enable`，以使服务器使用并行区块生成，设置为 `false`、`off` 或 `disabled` 时以禁用并行区块生成。
  io-threads:
    default: "-1"
    description: >-
      设置用于区块读写操作的线程数量。

      - 如果设置为任何小于零的值，将仅使用一个线程，对于一些大厅、小游戏等对 IO 读写要求不高的，可以设置为 1 或 2 来节省资源。
  worker-threads:
    default: "-1"
    description: >-
      设置用于并行区块生成的线程数量。

      - 如果设置为任何小于零的值，服务器将根据可用的物理 CPU 核心数量（**而不是逻辑核心**）自动确定最佳线程数量。

      - 对于拥有 3 个或更少物理核心的系统，仅使用 1 个线程。在所有其他情况下，线程数量被限制为物理核心数量的一半，对于一些大厅、小游戏等没有区块生成需求的，可以设置为 1 或 2 来节省资源。
collisions:
  enable-player-collisions:
    default: "true"
    description: >-
      是否允许玩家相互碰撞。

      - 此选项可能会被与记分板交互的插件破坏。如果在使用此选项时遇到问题，请尝试在未安装插件的情况下使用。
  send-full-pos-for-hard-colliding-entities:
    default: "true"
    description: >-
      是否允许船只和矿车的碰撞通常会受到客户端/服务器不一致的影响，这可能会导致玩家出现异常行为。

      - 此设置尝试通过发送涉及碰撞的实体的精确位置来缓解这种不同步。启用此功能将使用更多带宽；然而，在大多数情况下，这是一个值得的权衡。
commands:
  suggest-player-names-when-null-tab-completions:
    vanilla: "false"
    default: "true"
    description: >-
      是否在没有其他补全选项时，通过 Tab 补全返回玩家列表。
  time-command-affects-all-worlds:
    vanilla: "true"
    default: "false"
    description: >-
      是否允许 `/time` 命令对所有世界生效，还是仅对发送者的当前世界生效。
  ride-command-allow-player-as-vehicle:
    default: "false"
    description: 是否允许在原版的 `/ride` 命令中将实体装载到玩家身上。
console:
  enable-brigadier-completions:
    default: "true"
    description: >-
      是否在控制台中启用 Mojang 的 Brigadier（高级）命令补全。
  enable-brigadier-highlighting:
    default: "true"
    description: 是否在控制台中启用 Mojang 的 Brigadier 突出显示。
  has-all-permissions:
    default: "false"
    description: 是否启用在控制台命令发送者拥有所有权限。
item-validation:
  display-name:
    vanilla: "2147483647"
    default: "8192"
    description: 设置物品显示名称的最大长度，以字符为单位。
  lore-line:
    vanilla: "2147483647"
    default: "8192"
    description: 设置物品说明文本行的最大长度，以字符为单位。
  resolve-selectors-in-books:
    vanilla: "true"
    default: "false"
    description: >-
      是否解析书中的选择器。

      - 启用此功能后，拥有创造模式权限的玩家将能够以另一种方式使服务器崩溃。
  book:
    author:
      vanilla: "2147483647"
      default: "8192"
      description: 设置书的作者名称的最大长度，以字符为单位。
    page:
      vanilla: "2147483647"
      default: "16384"
      description: 设置书的页面的最大长度，以字符为单位。
    title:
      vanilla: "2147483647"
      default: "8192"
      description: 设置书的标题的最大长度，以字符为单位。
  book-size:
    page-max:
      vanilla: disabled
      default: "2560"
      description: >-
        设置一本书的单页可以贡献给书籍允许的总字节数的最大字节数，或者设置为 “disabled” 以禁用对书籍大小的非原版限制。
    total-multiplier:
      default: "0.98"
      description: >-
        设置每一页都有上一页字节数的这个百分比作为对书籍允许的总字节数的贡献（第一页的百分比为 1.0）。
logging:
  deobfuscate-stacktraces:
    default: "true"
    description: >-
      是否在日志中将 Spigot 的堆栈跟踪映射重新映射为 Mojang 的映射。对 Mojang 映射的服务器没有影响。
messages:
  no-permission:
    default: >-
      <red>I'm sorry, but you do not have permission to perform this command.
      Please contact the server administrators if you believe that this is in
      error.
    description: >-
      设置当玩家权限不足无法执行某个操作时，默认发送给玩家的消息，格式化为 [MiniMessage](https://docs.advntr.dev/minimessage/)。

      - 插件可以覆盖此消息以用于其命令。

      - 中文翻译：<red>很抱歉，您没有权限执行此命令。如果您认为这是错误的，请联系服务器管理员。
  use-display-name-in-quit-message:
    default: "false"
    description: >-
      是否在退出消息中使用玩家的显示名称（由插件设置）或实际名称。
  kick:
    authentication-servers-down:
      default: "<lang:multiplayer.disconnect.authservers_down>"
      description: >-
        设置当 Mojang 的认证服务器无法访问时发送给玩家的消息，格式化为 [MiniMessage](https://docs.advntr.dev/minimessage/)。

        - <lang:multiplayer.disconnect.authservers_down> 为调用客户端语言文本。
    connection-throttle:
      default: Connection throttled! Please wait before reconnecting.
      description: >-
        设置当玩家因连接过于频繁而被限制时发送给玩家的消息，格式化为 [MiniMessage](https://docs.advntr.dev/minimessage/)。

        - 中文翻译：因连接过于频繁而被限制！请等待后再重新连接。
    flying-player:
      default: "<lang:multiplayer.disconnect.flying>"
      description: >-
        设置发送给被检测到飞行的玩家的消息，格式化为 [MiniMessage](https://docs.advntr.dev/minimessage/)。

        - <lang:multiplayer.disconnect.flying> 为调用客户端语言文本。
    flying-vehicle:
      default: "<lang:multiplayer.disconnect.flying>"
      description: >-
        设置发送给被检测到乘坐飞行载具的玩家的消息，格式化为 [MiniMessage](https://docs.advntr.dev/minimessage/)。

        - <lang:multiplayer.disconnect.flying> 为调用客户端语言文本。
misc:
  fix-entity-position-desync:
    vanilla: "false"
    default: "true"
    description: >-
      是否修复实体位置不同步。

      - 这个功能修复了 [MC-4](https://bugs.mojang.com/browse/MC-4)。
  load-permissions-yml-before-plugins:
    default: "true"
    description: >-
      是否在插件启用之前加载 Bukkit 的 `permission.yml` 文件，使它们能够在启用时立即检查其中设置的信息。
  max-joins-per-tick:
    vanilla: "2147483647"
    default: "5"
    description: >-
      设置在单个刻中可以加入服务器的最大玩家数量。

      - 如果有更多玩家加入，他们将被推迟到后续刻中加入，但不会被踢出。这与 `bukkit.yml` 中的连接限制无关。
  region-file-cache-size:
    default: "256"
    description: 设置区域文件缓存的最大大小
  use-alternative-luck-formula:
    default: "false"
    description: >-
      使用一个[替代的运气公式](https://gist.github.com/aikar/40281f6c73ec9b6fef7588e6461e1ba9)。

      - 允许将运气应用于没有定义质量的物品。这会对钓鱼公式进行重大更改。
  use-dimension-type-for-custom-spawners:
    default: "false"
    description: >-
      是否允许幻翼、流浪商人等在自定义主世界中生成。

      - 默认为 `false`，以匹配原版行为。
  strict-advancement-dimension-check:
    default: "false"
    description: >-
      是否禁用将使用与主世界、下界或末地相同生成方式的世界翻译为通用维度，而不是该世界的特定维度键。
  chat-threads:
    chat-executor-core-size:
      default: "-1"
      description: 设置聊天线程池中保持的最小线程数
    chat-executor-max-size:
      default: "-1"
      description: >-
        设置聊天线程池中允许的最大线程数。

        - 默认值为 `-1`，表示没有最大限制，不需要聊天的服务器（如：监狱）可以设置为 1。
  client-interaction-leniency-distance:
    default: default
    description: >-
      设置在验证交互数据包时，服务器为玩家的交互范围添加的宽容距离。
  compression-level:
    default: default
    description: >-
      设置网络数据包的压缩级别。

      - 更高的压缩级别意味着更少的数据传输，但会消耗更多的 CPU 时间。默认值为 `-1`，表示服务器将使用定义的压缩器的默认值。

      - 请注意，Paper 当前使用的是 Velocity 压缩器，其默认压缩级别为 6，这是在性能和数据传输之间的一个折中方案。
  xp-orb-groups-per-area:
    default: default
    description: >-
      设置在特定区域内可以存在的相同价值的经验球组的数量。

      - 默认情况下，服务器使用 40。原版的合并算法不会合并不共享相同价值的经验球。
packet-limiter:
  all-packets:
    action:
      default: KICK
      description: >-
        设置超过限制时应采取的措施。

        - 可选的值为 `DROP`（将忽略超过限制的数据包）和 `KICK`（将因超过限制而踢出玩家）。
    interval:
      vanilla: "-1"
      default: "7.0"
      description: 设置 `max-packet-rate` 应用的时间间隔，单位为秒。
    max-packet-rate:
      default: "500.0"
      description: 设置在时间间隔内每个玩家允许的数据包数量。
  kick-message:
    default: "<red><lang:disconnect.exceeded_packet_rate>"
    description: >-
      设置当玩家发送过多数据包而被踢出时发送的消息，格式化为 [MiniMessage](https://docs.advntr.dev/minimessage/)。
  overrides:
    default: ServerboundPlaceRecipePacket
    description: >-
      设置覆盖任何单个命名数据包的全局配置。

      - 您可以在计时信息中找到每个数据包的名称。对于经验丰富的用户，这里命名的数据包将使用 Mojang 映射，无论服务器如何。
player-auto-save:
  max-per-tick:
    default: "-1"
    description: >-
      设置在单次 Tick 中最多应保存多少玩家。

      - 设置为 `-1` 将根据 `player-auto-save.rate` 的值（10 或 20）设置一个推荐值。
  rate:
    default: "-1"
    description: >-
      设置玩家数据应多久保存一次，单位为 Tick。

      - 设置为 `-1` 将使用 `bukkit.yml` 中的 `ticks-per.autosave`。
proxies:
  proxy-protocol:
    default: "false"
    description: >-
      是否应处理 [PROXY Protocol](https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt) 消息。

      - 这与 Velocity 或 BungeeCord 完全无关。仅在使用 HAProxy 或类似工具时启用此功能。
  bungee-cord:
    online-mode:
      default: "true"
      description: >-
        是否在位于 BungeeCord 后端时如何处理玩家 UUID 和数据。

        - 应该始终将其设置为与代理的在线模式设置相匹配。
  velocity:
    enabled:
      default: "false"
      description: 是否应接受 Velocity 现代转发。
    online-mode:
      default: "true"
      description: >-
        是否在位于 Velocity 后端时如何处理玩家 UUID 和数据。

        - 应该始终将其设置为与代理的在线模式设置相匹配。
    secret:
      default: ""
      description: >-
        设置你的 Velocity 代理和此服务器共享的密钥字符串。

        - 这需要与代理在 `forwarding.secret` 文件中定义的密钥匹配。
scoreboards:
  save-empty-scoreboard-teams:
    default: "true"
    description: >-
      是否允许一些记分板插件会留下数百个空的记分板队伍，这会显著减慢登录时间。此选项设置服务器是否应自动移除这些空队伍。
  track-plugin-scoreboards:
    default: "false"
    description: >-
      是否应跟踪仅包含虚拟目标的插件记分板。

      - 这是一个破坏性变更；然而，它提供了一个更合理的默认值。启用此功能时，使用记分板功能的插件可能会导致性能下降。
spam-limiter:
  incoming-packet-threshold:
    vanilla: "2147483647"
    default: "300"
    description: >-
      设置服务器认为传入数据包是垃圾邮件并忽略它们的阈值。
  recipe-spam-increment:
    default: "1"
    description: >-
      设置当玩家按下配方时，配方垃圾邮件计数器增加的数值。
  recipe-spam-limit:
    default: "20"
    description: >-
      设置配方垃圾邮件计数器可以达到的数值，直到服务器因垃圾邮件将玩家踢出。
  tab-spam-increment:
    default: "1"
    description: >-
      设置当玩家在聊天窗口按下Tab键时，内部Tab垃圾邮件计数器增加的数值。
  tab-spam-limit:
    default: "500"
    description: >-
      设置内部Tab垃圾邮件计数器可以达到的数值，直到服务器因垃圾邮件将玩家踢出。
spark:
  enabled:
    default: "true"
    description: 是否启用 Paper 自带的 Spark 性能分析器。
  enable-immediately:
    default: "false"
    description: >-
      是否在尽可能早的时候启用自带的 Spark 性能分析器。

      - 这在启动期间对服务器进行性能分析时非常有用。默认情况下，Spark 在服务器启动完成后启用（当控制台中发送 **Done (X.XXXs)! For help, type "help"** 消息时）。
timings:
  enabled:
    default: "false"
    description: 是否启用 Paper 自带的 Timings V2 性能分析器。
  hidden-config-entries:
    default: "[database, proxies.velocity.secret]"
    description: 设置在 Timings 报告中隐藏的配置项。
  history-interval:
    default: "300"
    description: 设置 Timings 报告中各点之间的时间间隔，单位为秒。
  history-length:
    default: "3600"
    description: >-
      设置为单个报告保留的数据总量。

      - 此值在服务器端进行验证。过大的报告将被拒绝。
  server-name:
    default: Unknown Server
    description: >
      设置 Timings 在服务器名称中填写什么内容。

      - 如果后端服务器过多的话，可以有效的帮助区别服务器。
  server-name-privacy:
    default: "false"
    description: 设置 Timings 在报告中隐藏服务器名称信息。
  url:
    default: "https://timings.aikar.co"
    description: >-
      设置自定义 [Timings](https://github.com/aikar/timings) 报告的服务器
  verbose:
    default: "true"
    description: >-
      设置 Timings 在其报告中提供更具体的信息。

      - 例如，特定的实体类型会导致延迟，而不仅仅是“实体”
unsupported-settings:
  inline-docs-warning:
    color: red
    message: >-
      **不支持的设置**


      以下设置由 Paper 提供，但未得到官方支持。
      使用它们需自行承担风险，并且它们可能会随时被移除。
  allow-headless-pistons:
    vanilla: "true"
    default: "false"
    description: >-
      是否允许创建无头活塞。

      - 这些通常用于破坏永久方块，一些破基岩的机器需要用到。
  allow-permanent-block-break-exploits:
    vanilla: "true"
    default: "false"
    description: >-
      是否可以通过原版漏洞破坏不可破坏的方块。

      - 这包括基岩、末地传送门框架、末地传送门方块等。
  allow-piston-duplication:
    vanilla: "true"
    default: "false"
    description: >-
      是否允许复制TNT、地毯和轨道。

      - 这不会控制沙子的复制。
  skip-vanilla-damage-tick-when-shield-blocked:
    default: "false"
    description: >-
      是否在实体通过盾牌阻挡伤害时跳过伤害 Tick。

      - 虽然原版会处理一个伤害 Tick，但这种行为在 Paper 中是一个长期存在的错误。启用此选项意味着将跳过伤害计时，这可能会导致盾牌上的快速伤害，因为缺少了无敌时间。
  perform-username-validation:
    vanilla: "false"
    default: "true"
    description: >-
      是否应该验证用户名。

      - 虽然这可能允许用户名中包含特殊字符的用户加入，但也可能会导致命令和插件出现问题。
  compression-format:
    default: ZLIB
    description: >-
      设置自定义保存区域文件的压缩格式。

      - 这支持 ZLIB、GZIP、LZ4 和 NONE，其中 NONE 表示可以禁用压缩。
      这会覆盖 server.properties 中的的 [region-file-compression](/paper/reference/server-properties/#region_file_compression)
  allow-unsafe-end-portal-teleportation:
    vanilla: "true"
    default: "false"
    description: >-
      是否启用与末地传送门传送相关的漏洞，例如沙子复制。

      - 不推荐启用此设置，但为有需求的人提供此选项。
  skip-tripwire-hook-placement-validation:
    vanilla: "true"
    default: "false"
    description: >-
      是否启用与绊线钩复制相关的漏洞。
  update-equipment-on-player-actions:
    vanilla: "false"
    default: "true"
    description: >-
      是否允许在处理某些玩家行为时更新装备。

      - 如果设置为 false，这将允许玩家通过例如在使用装备之前切换装备来利用属性。
watchdog:
  early-warning-delay:
    default: "10000"
    description: >-
      设置在服务器开始卡住后，看门狗线程开始打印线程转储之前的毫秒数。
  early-warning-every:
    default: "5000"
    description: >-
      设置在服务器卡住时打印线程转储的间隔，单位为毫秒。
