<permission>:
  default:
    description: |
      默认授予此权限的对象。

      "true": 所有玩家。

      "false": 没有玩家。

      "op": 仅限管理员（也别名为“isop”、“operator”、“isoperator”、“admin”和“isadmin”）。

      "!op": 所有玩家，除了管理员（也别名为“notop”、“!operator”、“notoperator”、“!admin”、“notadmin”）。
    default: "op"
  children:
    header:
      message: 一个子权限的列表（未显示）或一个子权限的映射（如下所示）。
    <permission>:
      description: |
        这个权限的一个子权限。

        该值是一个布尔值，其中 `false` 表示反转是否授予此权限。

        或者是一个顶级权限条目，
        除了默认值是此父权限的默认值，
        并且新创建的权限的任何子权限都会被提升到顶级。
      default: "true"
  description_:
    description: 该权限的描述。
