accept-transfers:
  default: "false"
  description: >
    是否接受来自其他服务器使用传输命令/数据包的传输。

    - 如果设置为 false，服务器将断开客户端的连接
allow-flight:
  default: "false"
  description: >
    是否允许玩家在生存模式中开启飞行的时候不踢出玩家。

    - 实测贴地飞行可以绕过检测，这种情况很可能是通过作弊实现的，但也可能会出现误判，建议使用第三方反作弊插件时关闭这个功能，由反作弊提供判定。
allow-nether:
  default: "true"
  description: >
    是否开启加载和生成下界(也叫地狱)维度

    - 大厅，游戏等不需要下界的子服可以直接关闭以节省内存和 CPU 资源，也可以在 [bukkit.yml](/paper/reference/bukkit-configuration/#settings_allow_end) 中关闭末地。
broadcast-console-to-ops:
  default: "true"
  description: "是否将控制台命令输出发送给所有在线的管理员"
broadcast-rcon-to-ops:
  default: "true"
  description: "是否将 RCON 命令输出发送给所有在线的管理员"
bug-report-link:
  default: ""
  description: "设置一个用于客户端菜单中“报告服务器错误”按钮的 URL 值"
debug:
  default: "false"
  description: "是否启用服务器的调试（debug）模式"
difficulty:
  default: "easy"
  description: >
    设置定义服务器的难度。

    - 允许的值：“peaceful（和平）”、“easy（简单）”、“normal（普通）”、“hard（困难）”

    - 注意：设置的难度不同生物 AI 的活跃程度也不同，难度越高越占用 CPU 资源。
enable-command-block:
  default: "true"
  description: "是否开启命令方块，玩家获取方块仍然需要 OP 权限"
enable-jmx-monitoring:
  default: "false"
  description: >
    是否启用 JMX 监控。

    - 公开一个对象名称为 “net.minecraft.server:type=Server” 的 MBean（管理构件），
      以及 “averageTickTime”（平均滴答时间）和 “tickTimes”（滴答次数）这两个属性，以毫秒为单位展示 TickTime。

    - 为了在 Java 运行时启用 JMX，你需要在启动时添加一些 JVM 参数，具体参数和配置方法可以参考 [Oracle 官方文档](https://docs.oracle.com/javase/8/docs/technotes/guides/management/agent.html)
enable-query:
  default: "false"
  description: "是否启用 GameSpy4 协议服务器监听器。用于第三方软件获取服务器的信息"
enable-rcon:
  default: "false"
  description: "是否启用 RCON 协议，允许其他控制软件对服务器控制台的远程访问"
enable-status:
  default: "true"
  description: >
    是否启用用于获取服务器信息的监听器，使服务器出现在客户端服务器列表中。

    - 如果关闭此功能，服务器将显示为离线状态，但玩家仍然可以连接。

    - 原理是通过将服务器状态上传到官方服务器，客户端在网络受限的情况下能够更快的获取信息，子服状态下可以关闭以节省带宽，客户端获取状态直接由反代理端（velocity/waterfall/BungeeCord）响应
enforce-secure-profile:
  default: "true"
  description: "是否启用 Mojang 公钥验证，没有 Mojang 签名的公钥的玩家将无法连接到服务器"
enforce-whitelist:
  default: "false"
  description: "是否启用白名单功能，启用后只有 whitelist.json 内的玩家才能连接到服务器"
entity-broadcast-range-percentage:
  default: "100"
  description: >
    设置向客户端发送的实体渲染距离，较高的值意味着它们可以从更远的地方被渲染，可能会导致更多的数据包发送以增加延迟。

    - 这模仿了客户端视频设置中的功能（与渲染距离类似，只要在服务器设置之下，客户端可以自定义），必须为 10% 到 1000% 之间的值
force-gamemode:
  default: "false"
  description: >
    是否强制玩家以默认游戏模式加入。

    - 这将在他们重新连接时重置他们之前的游戏模式
function-permission-level:
  default: "2"
  description: >
    设置函数的默认权限级别。

    - 允许的值：1、2、3、4
      详情请见 [Wiki](https://zh.minecraft.wiki/w/%E6%9D%83%E9%99%90%E7%AD%89%E7%BA%A7) 说明。
gamemode:
  default: "survival"
  description: >-
    设置玩家加入服务器的默认游戏模式。

    - （允许的值：“survival（生存）”、“creative（创造）”、“adventure（冒险）”、“spectator（旁观者）”）
generate-structures:
  default: "true"
  description: >-
    是否允许生成结构（如村庄）

    - 由于地牢和沙漠水井在技术上属于地物，因而即使此项设为 false，其仍然会生成，除非禁用结构所在的群戏。
generator-settings:
  default: "{}"
  description: >-
    设置用于自定义世界生成的设置。

    - 需要遵循[其格式](https://minecraft.wiki/w/Java_Edition_level_format#generatorOptions_tag_format)并编写相应的 JSON 字符串。

    - 例如：{"layers"\\:[{"height"\\:1,"block"\\:"minecraft\\:air"}],"lakes"\\:false,"features"\\:false,"biome"\\:"minecraft\\:the_void","structure_overrides"\\:[]}
      这会生成一个群戏为 the_void 使用空气（air）方块填充的世界。
hardcore:
  default: "false"
  description: "是否开启硬核模式，如果设置为 true，玩家死亡后将被设置为旁观者模式"
hide-online-players:
  default: "false"
  description: "是否在客户端请求数据包时隐藏数据包中的发送的玩家列表"
initial-disabled-packs:
  default: ""
  description: "设置在创建世界时不会自动启用的数据包列表，用英文逗号（,）分隔列表"
initial-enabled-packs:
  default: "vanilla"
  description: "设置在创建世界时需要启用的数据包列表，用英文逗号（,）分隔列表。一些功能包需要明确启用"
level-name:
  default: "world"
  description: "设置默认的世界名称，这也是保存世界数据的文件夹的名称"
level-seed:
  default: ""
  description: >
    设置用于生成世界的种子，留空则默认为随机。

    - 部分其他开发的服务端会有更大的种子计算方式，列如 [Luminol](https://github.com/LuminolMC/Luminol) 的 1024 位的种子生成规则
level-type:
  default: "minecraft:normal"
  description: >
    设置默认的世界生成器的类型。

    - 允许的值：`"normal（默认）"`、`"flat（超平坦）"`、`"large_biomes（巨型生物群系）"`、`"amplified（放大化）"`、`"single_biome_surface（单一生物群系）"`、`"buffet"`、`"default_1_1"`、`"customized（自定义）"`
log-ips:
  default: "true"
  description: >-
    是否应该记录客户端的 IP 地址。

    - 这不会和记录客户端 IP 地址的插件冲突。
max-chained-neighbor-updates:
  default: "1000000"
  description: >
    设置在一个方块发生变化时，比如被放置、破坏或状态改变之后触发其相邻方块更新的最大数量。

    - 设置为负（-1）以禁用更新（视情况而定，完全不需要方块更新的可以关闭）。
max-players:
  default: "20"
  description: "设置允许同时在线的最大玩家数量。"
max-tick-time:
  default: "60000"
  description: >
    设置在监视进程强制杀死服务器进程之间，每个游戏刻(Tick)最大可运算的时间，单位为毫秒。

    - 如果服务器在此时间内未完成处理一个游戏刻，监视进程将认为服务器已崩溃，并通过调用 System.exit(1) 强制关闭服务器。
      如果设置为 -1，则禁用此功能。
max-world-size:
  default: "29999984"
  description: >
    设置最大允许的世界半径，单位为一个方块。

    - 这只会影响创建世界时的[边界大小](https://zh.minecraft.wiki/w/%E4%B8%96%E7%95%8C%E8%BE%B9%E7%95%8C)，而不是世界的生成大小，可以用来禁止玩家去边界之外的地方。
motd:
  default: "A Minecraft Server"
  description: "设置服务器的 motd 信息。这将显示在客户端中的服务器列表中。"
network-compression-threshold:
  default: "256"
  description: >
    设置网络数据包压缩阈值，超过该数值的数据包将被压缩，单位为字节。

    - 设置为负数（-1）以禁用压缩。后端服务器（子服）建议在和代理端同一个局域网时关闭以节省不必要的 CPU 资源计算。
online-mode:
  default: "true"
  description: >
    是否强制将客户端所使用的账号与 Minecraft 认证服务器上的数据进行比对（也就是正版验证）。

    - 设置为 false 时将使用离线模式，建议安装一些登录插件来保护服务器免受离线账号的攻击。
op-permission-level:
  default: "4"
  description: >
    设置被赋予管理员权限时，该玩家可以执行的命令的最大权限等级。

    - 可设定值为：0, 1, 2, 3, 4
      详情请见 [Wiki](https://zh.minecraft.wiki/w/%E6%9D%83%E9%99%90%E7%AD%89%E7%BA%A7) 说明。
pause-when-empty-seconds:
  vanilla: "60"
  default: "-1"
  description: >
    设置服务器内没有玩家时候，经过多少秒后暂停服务器以节省资源（原版默认为 60）。

    - 默认禁用，因为其与某些在玩家下线时有额外行为，比如空闲时进行数据处理的插件不兼容。
player-idle-timeout:
  default: "0"
  description: >
    设置此项为非零的整数时服务器将会在玩家挂机超过指定的分钟数后将其踢出服务器。(默认为 0)

    - 客户端如若发送以下的数据包，将会停止该计时器:
      "点击活版门"，"物品附魔"，"更新告示牌文字"，"挖掘方块"，"放置方块"，"改变手持物品"，"甩手动作"，"实体动作"，
      "客户端状态"，"发送信息"，"右键实体"等。
prevent-proxy-connections:
  default: "false"
  description: >
    是否将玩家的 ISP/AS 与 Mojang Studios 身份验证服务器的 ISP/AS 进行对比

    - 如果不同将禁止该玩家加入服务器，通常这会禁止一些使用 VPN 的玩家进入。
pvp:
  default: "true"
  description: "是否禁止玩家之间攻击，这无法防止一些利用 TNT 和火焰的玩家"
query.port:
  default: "25565"
  description: >
    设置查询协议的服务器端口。

    - 当 enable-query 为 true 时，它将用于获取有关服务器的信息。"
rate-limit:
  default: "0"
  description: >
    设置客户端最大发包数量。超过该阈值将被踢出。
    设置为 0 以禁用。
rcon.password:
  default: ""
  description: "设置 rcon 协议所使用的密码。"
rcon.port:
  default: "25575"
  description: "设置在服务器上启用 rcon 时，rcon 服务器所绑定的端口。"
region-file-compression:
  default: "deflate"
  description: >
    设置指定压缩块(region)文件所用的压缩方式。

    - 可指定值为 "deflate", "lz4" 或 "none" 建议在类似 NAS 的硬盘环境中设置为 "none"。

    - 如果设置为 "none"，块文件将占用更多的磁盘空间，但与文件系统级的压缩一起使用可能会使其更有意义。
require-resource-pack:
  default: "false"
  description: "是否强制客户端必须下载服务器资源包才能连接到服务器。否则客户端将被踢出服务器。"
resource-pack:
  default: ""
  description: "设置客户端下载服务器资源包的 URL。"
resource-pack-id:
  default: ""
  description: "设置服务器资源包所使用的 UUID。"
resource-pack-prompt:
  default: ""
  description: "设置当服务端提醒客户端需要下载资源包时显示的提示信息。"
resource-pack-sha1:
  default: ""
  description: >
    设置资源包的哈希值。

    - 设置该项后客户端将验证对比本地下载的资源包的哈希值，以使玩家下载正确的资源包。
server-ip:
  default: ""
  description: >
    设置服务器绑定到的 IP 地址。

    - 后端服务器（子服）建议指向代理端 IP ，如果后端和代理端在同一个系统内则可以使用 127.0.0.1，留空则向全局广播。
server-port:
  default: "25565"
  description: "设置客户端连接到服务器的端口，默认为 25565 时客户端可以直接添加 IP 不需要填写端口。"
simulation-distance:
  default: "10"
  description: >
    设置服务端运算的实体与玩家之间的最大距离，其将在玩家的各个方向上检测(以半径而非直径计算)。

    - 如果实体超出此半径，则服务器不会对其进行运算，玩家也不会看见这些实体。
      这个数值建议应介于 3 到 32 之间。
spawn-monsters:
  default: "true"
  description: "是否生成怪物（骷髅，僵尸等敌对玩家的生物）。"
spawn-protection:
  default: "16"
  description: >
    设置出生点保护范围的边长，长度为 2x+1。

    - 设定值为 1 时将会使其**边长为 3**。
      将其设定为 0 以禁用出生点保护。如若启用，数值必须是大于 1 的整数。
sync-chunk-writes:
  default: "true"
  description: |
    是否启用异步写入区块数据。

    - 在 Paper 上这默认是无效的，除非[对应的设置](/paper/reference/system-properties#paperenable-sync-chunk-writes)被设置为 true。
text-filtering-config:
  default: ""
  description: "设置指定的文本过滤配置文件的路径。留空禁用本配置项。"
text-filtering-version:
  default: "0"
  description: |
    设置为 [`text-filtering-config`](#text_filtering_config) 指定的配置格式。
    有效值为 0 或 1。
use-native-transport:
  default: "true"
  description: "是否为 Linux 启用专用的优化来提升服务器性能，这只对 Linux 有用。"
view-distance:
  default: "10"
  description: >
    设置服务器向客户端发送的区块视距，以玩家为中心，以区块为单位的范围（半径，而非直径）。

    - 它决定了客户端的可视距离（默认值：10，最小值：3，最大值：32）。
white-list:
  default: "false"
  description: >
    是否在服务器上启用白名单。

    - 启用后，只有在白名单中（whitelist.json）的玩家才能连接到服务器。
