accept-transfers:
  default: "false"
  description: "是否接受来自其他服务器使用传输命令/数据包的传输。如果设置为 false，服务器将断开客户端的连接"
allow-flight:
  default: "false"
  description: "是否允许玩家在生存模式中开启飞行的时候不踢出玩家。这种情况很可能是通过作弊实现的，但也可能会出现误判"
allow-nether:
  default: "true"
  description: "是否开启下界维度生成。大厅，游戏等不需要下界的子服可以直接关闭"
broadcast-console-to-ops:
  default: "true"
  description: "是否将控制台命令输出发送给所有在线的管理员"
broadcast-rcon-to-ops:
  default: "true"
  description: "是否将 RCON 命令输出发送给所有在线的管理员"
bug-report-link:
  default: ""
  description: "设置一个用于客户端菜单中“报告服务器错误”按钮的 URL 值"
debug:
  default: "false"
  description: "是否启用服务器的调试（debug）模式"
difficulty:
  default: "easy"
  description: '设置定义服务器的难度。（允许的值：“peaceful（和平）”、“easy（简单）”、“normal（普通）”、“hard（困难）”）'
enable-command-block:
  default: "true"
  description: "是否开启命令方块，玩家获取方块仍然需要 OP 权限"
enable-jmx-monitoring:
  default: "false"
  description: >
    是否启用 JMX 监控
    公开一个对象名称为 “net.minecraft.server:type=Server” 的 MBean（管理构件），
    以及 “averageTickTime”（平均滴答时间）和 “tickTimes”（滴答次数）这两个属性，以毫秒为单位展示滴答时间。
    为了在 Java 运行时启用 JMX，你需要在启动时添加一些 JVM 参数，具体参数和配置方法可以参考 [Oracle 官方文档](https://docs.oracle.com/javase/8/docs/technotes/guides/management/agent.html)
enable-query:
  default: "false"
  description: "是否启用 GameSpy4 协议服务器监听器。用于获取服务器的信息"
enable-rcon:
  default: "false"
  description: "是否启用 RCON 允许对服务器控制台的远程访问"
enable-status:
  default: "true"
  description: >
    是否启用用于获取服务器信息的监听器，使服务器出现在服务器列表中。如果关闭此功能，服务器将显示为离线状态，但玩家仍然可以连接。
    子服状态下可以关闭以节省带宽，客户端获取状态直接由反代理端（velocity/waterfall/BungeeCord）响应
enforce-secure-profile:
  default: "true"
  description: "是否启用 Mojang 公钥验证，没有 Mojang 签名的公钥的玩家将无法连接到服务器"
enforce-whitelist:
  default: "false"
  description: "是否启用白名单功能，启用后只有 white-list 内的玩家才能连接到服务器"
entity-broadcast-range-percentage:
  default: "100"
  description: >
    设置向客户端发送的实体渲染距离，较高的值意味着它们可以从更远的地方被渲染，可能会导致更多的延迟。
    这模仿了客户端视频设置中的功能（与渲染距离类似，只要在服务器设置之下，客户端可以自定义）。这必须在10%到1000%之间
force-gamemode:
  default: "false"
  description: >
    是否强制玩家以默认游戏模式加入。这将在他们重新连接时重置他们之前的游戏模式
function-permission-level:
  default: "2"
  description: "设置函数的默认权限级别。（允许的值：1、2、3、4）"
gamemode:
  default: "survival"
  description: '设置玩家加入服务器的默认游戏模式。（允许的值：“survival（生存）”、“creative（创造）”、“adventure（冒险）”、“spectator（旁观者）”）'
generate-structures:
  default: "true"
  description: "是否允许生成结构（如村庄），由于地牢和沙漠水井在技术上属于地物，因而即使此项设为 false，其仍然会生成"
generator-settings:
  default: "{}"
  description: >-
    设置用于自定义世界生成的设置。需要遵循[其格式](https://minecraft.wiki/w/Java_Edition_level_format#generatorOptions_tag_format)并编写相应的 JSON 字符串。
    例如：{"layers"\:[{"height"\:1,"block"\:"minecraft\:air"}],"lakes"\:false,"features"\:false,"biome"\:"minecraft\:the_void","structure_overrides"\:[]}
hardcore:
  default: "false"
  description: "是否开启硬核模式，如果设置为 true，玩家死亡后将被设置为旁观者模式"
hide-online-players:
  default: "false"
  description: "是否在客户端请求数据包时隐藏数据包中的发送的玩家列表"
initial-disabled-packs:
  default: ""
  description: "设置在创建世界时不会自动启用的数据包列表，用英文逗号（,）分隔列表"
initial-enabled-packs:
  default: "vanilla"
  description: "设置在创建世界时需要启用的数据包列表，用英文逗号（,）分隔列表。一些功能包需要明确启用"
level-name:
  default: "world"
  description: "设置默认的世界名称，这也是保存世界数据的文件夹的名称"
level-seed:
  default: ""
  description: "设置用于生成世界的种子，留空则默认为随机。部分服务端会有更大的种子计算方式，列如：1024 位的种子生成规则"
level-type:
  default: "minecraft:normal"
  description: 设置世界生成器的类型。（允许的值：`"normal（默认）"`、`"flat（超平坦）"`、`"large_biomes（巨型生物群系）"`、`"amplified（放大化）"`、`"single_biome_surface（单一生物群系）"`、`"buffet"`、`"default_1_1"`、`"customized（自定义）"`）
log-ips:
  default: "true"
  description: >-
    Whether player IP addresses should be logged by the server. This does not
    impact the ability of plugins to log the IP addresses of players
max-chained-neighbor-updates:
  default: "1000000"
  description: >
    Limits the number of consecutive neighbor updates before skipping subsequent updates. Negative
    values will disable the limit.
max-players:
  default: "20"
  description: "The maximum number of players that can play on the server at the same time."
max-tick-time:
  default: "60000"
  description: >
    The maximum number of milliseconds a single tick may take before the server watchdog stops the
    server with the message. If a single server tick took 60.00 seconds (should be max 0.05) it will be considered to be
    crashed and the server will forcibly shutdown via calling System.exit(1). Setting this to -1 will disable watchdog
    entirely.
max-world-size:
  default: "29999984"
  description: >
    The maximum allowed size of the world radius, in blocks. This only affects the chunks that are
    generated when the world is initially created, and not the world border (Limited to 29999984).
motd:
  default: "A Minecraft Server"
  description: "The message of the day, displayed in the server list."
network-compression-threshold:
  default: "256"
  description: "The number of bytes of a packet before it is compressed. Setting to a negative disables compression."
online-mode:
  default: "true"
  description: >
    If set to true, the server checks all connecting players against Minecraft''s account database.
    This requires all connected players to have a valid Minecraft account and makes it impossible for cracked
    players to connect.
op-permission-level:
  default: "4"
  description: "Sets the default permission level for ops when using /op. (Allowed values: 0, 1, 2, 3, 4)"
pause-when-empty-seconds:
  vanilla: "60"
  default: "-1"
  description: >
    How many seconds have to pass after no player has been online before the server is paused.
    This is disabled by default because it is incompatible with what plugins expect and might do with no players online.
player-idle-timeout:
  default: "0"
  description: >
    If non-zero, players are kicked from the server if they are idle for more than that many minutes.
    (Default: 0). The following packets stop this timer: "Click Window", "Enchant Item", "Update Sign",
    "Player Digging", "Player Block Placement", "Held Item Change", "Animation (swing arm)", "Entity Action",
    "Client Status", "Chat Message", "Use Entity".
prevent-proxy-connections:
  default: "false"
  description: >
    If the ISP/AS sent from the server is different from the one from Mojang Studios'' authentication
    server, the player not allowed to join the server.
pvp:
  default: "true"
  description: "If set to false, players are not allowed to attack other players."
query.port:
  default: "25565"
  description: "The port for the query server. This is used to get information about the server."
rate-limit:
  default: "0"
  description: >
    Sets the maximum allowed number of packets that can be sent before getting kicked. Setting this to 0
    disables the limit.
rcon.password:
  default: ""
  description: "The password for the rcon server."
rcon.port:
  default: "25575"
  description: "The port to start the rcon server on."
region-file-compression:
  default: "deflate"
  description: >
    Specifies the compression type used to compress region files. Possible values are: "deflate", "lz4" and "none".
    If set to "none", region files will take up significantly more disk space, but it might make sense together with filesystem-level compression.
require-resource-pack:
  default: "false"
  description: "If true, a player must have the given resource pack to connect. They will be kicked if they do not have it."
resource-pack:
  default: ""
  description: "The URL to the server's resource pack. "
resource-pack-id:
  default: ""
  description: "The UUID of the server resource pack to use."
resource-pack-prompt:
  default: ""
  description: "The message that is displayed when the client is prompted to download the resource pack."
resource-pack-sha1:
  default: ""
  description: >
    The hash of the resource pack, used for verification. This is recommended to be set to ensure
    players are downloading the correct pack.
server-ip:
  default: ""
  description: "The IP address to bind to. Leave blank to bind to all interfaces."
server-port:
  default: "25565"
  description: "The port to listen on for connections."
simulation-distance:
  default: "10"
  description: >
    Sets the maximum distance from players that living entities may be located in order to be
    updated by the server, measured in chunks in each direction of the player (radius, not diameter).
    If entities are outside this radius, then they will not be ticked by the server nor will they be
    visible to players. Must be between 3 and 32 inclusive.
spawn-monsters:
  default: "true"
  description: "Determines if monsters will be spawned."
spawn-protection:
  default: "16"
  description: >
    Used to determine the side length of the spawn protection. The formula of 2x+1 is used. A value of 1
    will result in a side length of 3 **blocks**. Setting this to 0 will disable spawn protection. There must be
    at least 1 operator to be enabled.
sync-chunk-writes:
  default: "true"
  description: |
    Enables synchronous writing of chunk data. Has no effect on Paper by default, unless the corresponding system property is also set to true.
    See [the system properties reference](/paper/reference/system-properties#paperenable-sync-chunk-writes).
text-filtering-config:
  default: ""
  description: "The path to the text filtering configuration file. Leave blank to disable text filtering."
text-filtering-version:
  default: "0"
  description: |
    The version of the configuration format used for [`text-filtering-config`](#text_filtering_config).
    Valid values are 0 and 1.
use-native-transport:
  default: "true"
  description: "Provides a performance boost for Linux servers."
view-distance:
  default: "10"
  description: >
    设置服务器向客户端发送的世界数据量，以玩家为中心，以区块为单位测量每个方向的范围（半径，而非直径）。它决定了服务器端的可视距离（默认值：10，最小值：3，最大值：32）。
white-list:
  default: "false"
  description: "Enables a whitelist on the server. If enabled, the server will only allow selected users to connect."
